services:
  member-grocery-server:
    build: .
    container_name: member-grocery-server
    ports:
      - "3019:3001"
      - "3020:3002"
    volumes:
      - ./public/products:/app/public/products
      - ./public/profiles:/app/public/profiles
    env_file: .env
    networks:
      - dev_network
    restart: always

networks:
  dev_network:
    external: true
